### ISSUE TITLE
Python Command Line Template

### ISSUE THREAD

**Issue by Maikon** [vanilla-project/vanilla-project.guide#34]
A Python template similar to the Ruby one would be great. Every time I try to look into conventions on how to structure a Python app, it seems a bit like the wild west. Having a template with the why that template is a good starting point would be 👍

**Comment by christophgockel** [comment]
It kinda is a wild west in Python land. But there's _some_ sense in the chaos. ;)
Thanks for bringing it up. Since I do remember some Python it's definitely something we can tackle!

**Comment by Maikon** [comment]
Found [this](http://docs.python-guide.org/en/latest/writing/structure/) which seems pretty good.

**Comment by christophgockel** [comment]
Thanks again Makis! A Python guide has been added now in #39. :)
